services:
   backend:
    image: 176583374037.dkr.ecr.ap-south-1.amazonaws.com/complete-infra-app-backend:latest

    container_name: backend
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

   mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - /data/mysql/data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

   redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

   nginx:
    image: 176583374037.dkr.ecr.ap-south-1.amazonaws.com/complete-infra-app-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

   prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "169.254.169.254:169.254.169.254"
    networks:
      - app-network
    restart: unless-stopped

   grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin123
    - GF_AWS_DEFAULT_REGION=ap-south-1
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    - AWS_SDK_LOAD_CONFIG=true
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    - grafana_data:/var/lib/grafana
    networks:
    - app-network
    restart: unless-stopped
    depends_on:
    - prometheus

volumes:
  grafana_data:

networks:
  app-network:
    driver: bridge
