{
 "title": "Complete Infra Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "EC2 CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0c26d6e666af4aa02" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Network In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0c26d6e666af4aa02" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "InstanceId": "i-0c26d6e666af4aa02" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ALB Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/complete-infra-alb/2d7da2c3d18073ae"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ALB 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/complete-infra-alb/2d7da2c3d18073ae"
     },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ALB Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/complete-infra-alb/2d7da2c3d18073ae"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Healthy Hosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/complete-infra-alb/2d7da2c3d18073ae",
      "TargetGroup": "targetgroup/complete-infra-nginx-tg/acd4ca79e29b43eb"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0c26d6e666af4aa02" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "InstanceId": "i-0c26d6e666af4aa02" },
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}