server.port=8085
server.address=0.0.0.0

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.devops=INFO

spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.indent_output=true

# ======================
# Local MySQL Configuration (Commented Out)
# ======================
#spring.datasource.url=jdbc:mysql://mysql:3306/mydb
#spring.datasource.username=root
#spring.datasource.password=root

# ======================
# RDS MySQL Configuration
# ======================
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/mydb
spring.datasource.username=root
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis config
spring.redis.host=redis
spring.redis.port=6379
spring.cache.type=redis

# ======================
# Prometheus / Actuator Monitoring
# ======================
management.server.port=8086
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=demo-app
management.metrics.distribution.percentiles-histogram.http.server.requests=true