apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email-Alert
    receivers:
      - uid: webhook-receiver
        type: webhook
        settings:
          url: "http://172.18.0.1:5001"
          httpMethod: POST

policies:
  - orgId: 1
    receiver: Email-Alert
    group_by: ['alertname']
    group_wait: 30s
    repeat_interval: 4h
